/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import motores.IMotor;

/**
 *
 * @author silvi
 */
public class EditMotorJDialog extends javax.swing.JDialog {
    
    private static IMotor motor ;
    /**
     * Creates new form EditMotorJDialog
     */
    public EditMotorJDialog(java.awt.Frame parent, boolean modal, IMotor motor) {
        super(parent, modal);
        this.motor = motor;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloJLabel = new javax.swing.JLabel();
        altaJLabel = new javax.swing.JLabel();
        bajaJLabel = new javax.swing.JLabel();
        altaJPanel = new javax.swing.JPanel();
        altaJTextField = new javax.swing.JTextField();
        altaJButton = new javax.swing.JButton();
        ErrorAltaJLabel = new javax.swing.JLabel();
        bajaJPanel = new javax.swing.JPanel();
        bajaJTextField = new javax.swing.JTextField();
        bajaJButton = new javax.swing.JButton();
        ErrorBajaJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        tituloJLabel.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        tituloJLabel.setForeground(new java.awt.Color(153, 153, 153));
        tituloJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloJLabel.setText("GESTIÓN MOTOR");

        altaJLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        altaJLabel.setForeground(new java.awt.Color(153, 153, 153));
        altaJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        altaJLabel.setText("Alta palabra");

        bajaJLabel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        bajaJLabel.setForeground(new java.awt.Color(153, 153, 153));
        bajaJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bajaJLabel.setText("Baja palabra");

        altaJPanel.setBackground(new java.awt.Color(60, 60, 60));

        altaJTextField.setColumns(5);
        altaJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaJTextFieldActionPerformed(evt);
            }
        });

        altaJButton.setText("Alta");
        altaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaJButtonActionPerformed(evt);
            }
        });

        ErrorAltaJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout altaJPanelLayout = new javax.swing.GroupLayout(altaJPanel);
        altaJPanel.setLayout(altaJPanelLayout);
        altaJPanelLayout.setHorizontalGroup(
            altaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaJPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(altaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(altaJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ErrorAltaJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        altaJPanelLayout.setVerticalGroup(
            altaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(altaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altaJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ErrorAltaJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        bajaJPanel.setBackground(new java.awt.Color(60, 60, 60));

        bajaJTextField.setColumns(5);
        bajaJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaJTextFieldActionPerformed(evt);
            }
        });

        bajaJButton.setText("baja");
        bajaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaJButtonActionPerformed(evt);
            }
        });

        ErrorBajaJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bajaJPanelLayout = new javax.swing.GroupLayout(bajaJPanel);
        bajaJPanel.setLayout(bajaJPanelLayout);
        bajaJPanelLayout.setHorizontalGroup(
            bajaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaJPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(bajaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bajaJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bajaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ErrorBajaJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bajaJPanelLayout.setVerticalGroup(
            bajaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(bajaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bajaJButton)
                    .addComponent(bajaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorBajaJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(altaJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addComponent(bajaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altaJLabel)
                            .addComponent(bajaJLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(altaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(altaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bajaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bajaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altaJTextFieldActionPerformed

    private void bajaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaJTextFieldActionPerformed

    private void altaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaJButtonActionPerformed
        String palabra = altaJTextField.getText().toUpperCase();
        if (palabra.matches("[A-Z]{5}")) {
            if (!motor.checkPalabra(palabra)) {
                motor.add(palabra);
                ErrorAltaJLabel.setForeground(MainJFrame.COLOR_VERDE);
                ErrorAltaJLabel.setText("palabra dada de alta correctamente");
            }else{
                ErrorAltaJLabel.setForeground(MainJFrame.COLOR_ROJO);
                ErrorAltaJLabel.setText("Error. la palabra ya existe");                
            }

            
        }else{
            ErrorAltaJLabel.setForeground(MainJFrame.COLOR_ROJO);
            ErrorAltaJLabel.setText("Error. la palabra tiene que ser de 5 letras");
            
        }
    }//GEN-LAST:event_altaJButtonActionPerformed

    private void bajaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaJButtonActionPerformed
        String palabra = bajaJTextField.getText().toUpperCase();
        if (palabra.matches("[A-Z]{5}")) {
            if (motor.checkPalabra(palabra)) {
                motor.remove(palabra);
                ErrorBajaJLabel.setForeground(MainJFrame.COLOR_VERDE);
                ErrorBajaJLabel.setText("palabra dada de baja correctamente");
            }else{
                ErrorBajaJLabel.setForeground(MainJFrame.COLOR_ROJO);
                ErrorBajaJLabel.setText("Error");                
            }

            
        }else{
            ErrorBajaJLabel.setForeground(MainJFrame.COLOR_ROJO);
            ErrorBajaJLabel.setText("Error. la palabra tiene que ser de 5 letras");
            
        }
    }//GEN-LAST:event_bajaJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMotorJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditMotorJDialog dialog = new EditMotorJDialog(new javax.swing.JFrame(), true, motor);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorAltaJLabel;
    private javax.swing.JLabel ErrorBajaJLabel;
    private javax.swing.JButton altaJButton;
    private javax.swing.JLabel altaJLabel;
    private javax.swing.JPanel altaJPanel;
    private javax.swing.JTextField altaJTextField;
    private javax.swing.JButton bajaJButton;
    private javax.swing.JLabel bajaJLabel;
    private javax.swing.JPanel bajaJPanel;
    private javax.swing.JTextField bajaJTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables
}
